export {default as Main} from './Main'
export {default as Catalog} from './Catalog'
export {default as Product} from './Product'
export {default as Cart} from './Cart'
export {default as Favorite} from './Favorite'